### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ImAbhishekTomar** [kohver/react-native-touchable-scale#4]
'TouchableScale' is declared but its value is never read.ts(6133)
Could not find a declaration file for module 'react-native-touchable-scale'. '/Users/jack/Desktop/root/outonox/source/app/quibik/node_modules/react-native-touchable-scale/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-touchable-scale` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-touchable-scale';`ts(7016)

**Comment by kohver** [comment]
Please provide a step-by-step way to reproduce this issue. I'm not very familiar with TypeScript. What command do you run for example?

And @RWOverdijk, may be you could help?

**Comment by RWOverdijk** [comment]
I have no idea, it works for me. Maybe the tsconfig is not pointing to the correct directory? What version of typescript is this?

Worst case we can add a types to the package.json to point to the file, but it shouldn't be needed.

**Comment by ImAbhishekTomar** [comment]
I will reproduce this and share steps soon.

**Comment by RWOverdijk** [comment]
@ImAbhishekTomar Thanks!

**Comment by giladpn** [comment]
@kohver @RWOverdijk I had a very similar issue (the message is below), and found what appears to be an easy solution. I believe the TypeScript compiler - at least under certain default configurations (not clear which) - looks for the definitions in `index.d.ts` rather than `react-native-touchable-scale.d.ts`. Sorry if I am not clear on the reasons, I am new to TypeScript.

So, solution was: 

You have already created a correct type description in the file `react-native-touchable-scale.d.ts`.
Do one of these: either

1. create another file called `index.d.ts` and copy-paste the contents of the former into the latter; or
2. just rename the former to `index.d.ts`

Hope this helps.

The error message was:
```
Could not find a declaration file for module 'react-native-touchable-scale'. 'c:/React-native-projects/safriend/node_modules/react-native-touchable-scale/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-touchable-scale` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-touchable-scale';`ts(7016)
```

**Comment by iduuck** [comment]
For now, you can "overwrite" the default declaration with the following declaration file (create a new file named "`react-native-touchable-scale.d.ts`"

```ts
declare module 'react-native-touchable-scale' {
  import React from "react";
  import { TouchableWithoutFeedbackProps } from "react-native";

  interface TouchableScaleProps extends TouchableWithoutFeedbackProps {
    defaultScale?: number
    activeScale?: number
    tension?: number
    friction?: number
    pressInTension?: number
    pressInFriction?: number
    pressOutTension?: number
    pressOutFriction?: number
    useNativeDriver?: boolean
  }

  declare const TouchableScale: React.ComponentType<TouchableScaleProps>;
  export default TouchableScale;
}

```

**Comment by L-Anghelo-Chinchilla** [comment]
![image](https://user-images.githubusercontent.com/50245303/100458835-cf8aa980-309a-11eb-86a1-a20102f5d021.png)

Can anyone explain this error to me? I have overwritten `react-native-touchable-scale.d.ts` and this error still occurs.

**Comment by iduuck** [comment]
Seems like you don't include the `react-native-touchable-scale.d.ts`. You are still using the old declaration.

EDIT: Which version are you using, since the latest github master push includes this one: https://github.com/kohver/react-native-touchable-scale/blob/master/react-native-touchable-scale.d.ts
