### ISSUE TITLE
Animated.View.propTypes.style removed in RN 62

### ISSUE THREAD

**Issue by bneigher** [kohver/react-native-touchable-scale#5]
https://github.com/facebook/react-native/issues/16542

Affected line: https://github.com/kohver/react-native-touchable-scale/blob/master/src/TouchableScale.js#L112

```
TouchableScale.propTypes = {
    ...TouchableWithoutFeedback.propTypes,
    style: Animated.View.propTypes.style,
    defaultScale: PropTypes.number.isRequired,
    activeScale: PropTypes.number.isRequired,
    tension: PropTypes.number.isRequired,
    friction: PropTypes.number.isRequired,
    pressInTension: PropTypes.number,
    pressInFriction: PropTypes.number,
    pressOutTension: PropTypes.number,
    pressOutFriction: PropTypes.number,
    useNativeDriver: PropTypes.bool,
};
```

Needs to change to use `ViewPropTypes.style`

**Comment by kohver** [comment]
Thank you for the report, @bneigher! I just fixed it, would be awesome if you'd confirm that it works ok now.

**Comment by sercanov** [comment]
I can confirm it works on iOS

**Comment by bneigher** [comment]
@kohver yes it works! thank you 🙌

**Comment by capsudo** [comment]
does not work on RN 0.63

TypeError: Cannot read property 'style' of undefined

when

```js
TouchableScale.propTypes = {
     ...TouchableWithoutFeedback.propTypes,
     style: ViewPropTypes.style,
```

due to `import { TouchableWithoutFeedback, Animated, ViewPropTypes } from 'react-native';` 


Indeed `ViewPropTypes` is not exported by RN 0.63 anymore. A workaround is to take it from the Libraries folder `import ViewPropTypes from 'react-native/Libraries/DeprecatedPropTypes/DeprecatedViewPropTypes';` but this should be avoided because, well, it's deprecated.


edit : https://codesandbox.io/s/react-native-touchable-scale-issue-5-x2miq?file=/src/App.js

**Comment by sajadghawami** [comment]
how is this fixable? i dont have any problems on ios, but i get this error on web
